#!/usr/bin/env bash

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

_global_variables() {
  start_date=""
  conf_dir=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "geth" \
    "go-ethereum"
}

_init() {
  local \
    _conf_dir="${1}" \
    _lib \
    _geth_opts=()
  _genesis="$( \
    _get_lib)/data-blockchain/genesis.json"
  _geth_opts+=(
    --datadir
      "${conf_dir}"
  )
  geth \
    "${_geth_opts[@]}" \
    init \
    "${_genesis}"
}

_conf_dir_auto_detect() {
  local \
    _conf_dir
  _conf_dir="${HOME}/.config/data-blockchain/init"
  if [[ "${conf_dir}" == "" ]]; then
    mkdir \
      -p \
      "${_conf_dir}" || \
      true
    chmod \
      700 \
      "${_conf_dir}"
  fi
  _set_override \
    "conf" \
    "dir" \
    "${_conf_dir}"
}


_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "start" \
    "date" \
    "$(_get_date_human)"
  _conf_dir_auto_detect
}

_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "               Start date:   ${start_date}"
  _msg_info "  Configuration directory:   ${conf_dir}"
}

while \
  getopts \
    'C:cvh?' \
    arg; do
  case \
    "${arg}" in
    C) override_conf_dir="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))

_globals
_global_variables
_requirements

_set_overrides
_show_config
app_opts=(
  "${conf_dir}"
)

_init \
  "${app_opts[@]}"
